name: Kubernetes Deploy

on:
  push:
    branches:
        - main

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: checkout
        uses: actions/checkout@v2
    
      - name: Deploy App(Deployment)
        uses: actions-hub/kubectl@master
        with: 
          args: apply -f kubernetes/deployment.yml

      - name: Deploy App(Deployment)
        uses: actions-hub/kubectl@master
        with: 
          args: apply -f kubernetes/service.yml 

      - name: Deploy App(Deployment)
        uses: actions-hub/kubectl@master
        with: 
          args: apply -f kubernetes/ingress.yml       